-- Update supplier profiles from SUPPLIERS INFORMATION-2.xlsx
-- email, contact, social media, and Facebook logo for all matched booths.
-- Logos use the stable graph.facebook.com/{page}/picture endpoint which
-- 302-redirects to the live profile photo and sends CORS allow-origin: *.

update stores set email = 'pjesman@brittanyhotelbgc.com', contact = '0956 791 4432', social_media = 'https://www.facebook.com/profile.php?id=61582007161012', logo_url = 'https://graph.facebook.com/61582007161012/picture?type=large' where id = 'store_ba01_brittany_mella';  -- BA1 Brittany Mella
update stores set email = 'invitationsbyten.details@gmail.com', contact = '0995 449 7070', social_media = 'https://www.facebook.com/invitationsbyten', logo_url = 'https://graph.facebook.com/invitationsbyten/picture?type=large' where id = 'store_46_invitations_by_ten';  -- BA10 Invitations by Ten
update stores set email = 'theperidotstudios@gmail.com', contact = '0947 998 1978, 0917 564 8684', social_media = 'https://www.facebook.com/peridotstudios', logo_url = 'https://graph.facebook.com/peridotstudios/picture?type=large' where id = 'store_09_timeless_portraits_peridot_stu';  -- BA11-14 Timeless Portraits Peridot Studios
update stores set email = 'sharondelight@gmail.com', contact = '0926 694 2956', social_media = 'https://www.facebook.com/profile.php?id=61565535772960', logo_url = 'https://graph.facebook.com/61565535772960/picture?type=large' where id = 'store_ba15_sharons_delight';  -- BA15 Sharon's Delight
update stores set email = 'sales.7thtrumpet@gmail.com', contact = '0917 877 1177', social_media = 'https://www.facebook.com/7thTrumpetPh', logo_url = 'https://graph.facebook.com/7thTrumpetPh/picture?type=large' where id = 'store_44_7th_trumpet_lights_sounds';  -- BA16 7th Trumpet Lights & Sounds
update stores set email = 'vaellajewelry@gmail.com', contact = '0906 530 9973', social_media = 'https://www.facebook.com/vaellajewelry', logo_url = 'https://graph.facebook.com/vaellajewelry/picture?type=large' where id = 'store_ba17_vaella_jewelry';  -- BA17 Vaella Jewelry
update stores set email = 'tupermala@gmail.com', contact = '0956 150 6610', social_media = 'https://www.facebook.com/profile.php?id=100066821853597', logo_url = 'https://graph.facebook.com/100066821853597/picture?type=large' where id = 'store_40_permala_photo_video';  -- BA18-20 Permala Photo & Video
update stores set email = 'jhossaeventmanagement@gmail.com', contact = '0977 208 2595', social_media = 'https://www.facebook.com/JhossaEM', logo_url = 'https://graph.facebook.com/JhossaEM/picture?type=large' where id = 'store_23_jhossa_events_mgt';  -- BA2-3 Jhossa Events Mgt.
update stores set email = '8pointstudioph@gmail.com', contact = '0961 031 8527' where id = 'store_38_8pointstudios';  -- BA22 8pointstudios
update stores set email = 'graciabellesflowershop@gmail.com', contact = '0961 423 2288, 0961 997 5658', social_media = 'https://www.facebook.com/profile.php?id=61555776146686', logo_url = 'https://graph.facebook.com/61555776146686/picture?type=large' where id = 'store_36_graciabelle_s_flowershop';  -- BA23 Graciabelle's Flowershop
update stores set email = 'jnp@realshipcorp.com', contact = '0917 509 9421', social_media = 'https://www.facebook.com/legworksevents', logo_url = 'https://graph.facebook.com/legworksevents/picture?type=large' where id = 'store_42_manila_yacht_cruises';  -- BA24 Manila Yacht Cruises
update stores set email = 'romierrejewelry@gmail.com', contact = '0915 279 0342, 09989913568', social_media = 'https://www.facebook.com/romierrejewelry', logo_url = 'https://graph.facebook.com/romierrejewelry/picture?type=large' where id = 'store_35_romierre_jewelry';  -- BA25 Romierre Jewelry
update stores set email = 'jenne@ajtevents.com', contact = '0917 626 4878, 09171271852', social_media = 'https://www.facebook.com/ajteventsmanagement', logo_url = 'https://graph.facebook.com/ajteventsmanagement/picture?type=large' where id = 'store_33_ajt_events';  -- BA26 AJT Events
update stores set email = 'info.shutterloop@gmail.com', contact = '0976 602 3266 | 0915 501 9649', social_media = 'https://www.facebook.com/shutterloop18', logo_url = 'https://graph.facebook.com/shutterloop18/picture?type=large' where id = 'store_32_shutterloop';  -- BA27 Shutterloop
update stores set email = 'coltanna18@gmail.com', contact = '0917 857 5757', social_media = 'https://www.facebook.com/profile.php?id=100095313474628', logo_url = 'https://graph.facebook.com/100095313474628/picture?type=large' where id = 'store_31_stageability_lights_sounds';  -- BA28 Stageability Lights & Sounds
update stores set email = 'emil15_ocampo@yahoo.com.ph', contact = '0917 500 5890', social_media = 'https://www.facebook.com/emilocampobridalgown', logo_url = 'https://graph.facebook.com/emilocampobridalgown/picture?type=large' where id = 'store_26_emil_ocampo';  -- BA30 Emil Ocampo
update stores set email = 'frompaulyn@gmail.com', contact = '0917 876 1813', social_media = 'https://www.facebook.com/FromPaulyn', logo_url = 'https://graph.facebook.com/FromPaulyn/picture?type=large' where id = 'store_ba31_from_paulyn';  -- BA31 From Paulyn
update stores set email = 'book.katesconfections@gmail.com', contact = '0977 121 9649', social_media = 'https://www.facebook.com/katesconfectionsph', logo_url = 'https://graph.facebook.com/katesconfectionsph/picture?type=large' where id = 'store_24_kate_s_confections';  -- BA32 Kate's Confections
update stores set email = 'lukasbuttersteaks@gmail.com', contact = '927 332 2624', social_media = 'https://www.facebook.com/lukasbuttersteaksbetterliving', logo_url = 'https://graph.facebook.com/lukasbuttersteaksbetterliving/picture?type=large' where id = 'store_ba33_lukas_steak';  -- BA33 Luka's Steak
update stores set email = 'sales@fenrirsforest.com', contact = '0917 882 2667', social_media = 'https://www.facebook.com/fenrirsforest', logo_url = 'https://graph.facebook.com/fenrirsforest/picture?type=large' where id = 'store_20_fenrir_s_forest';  -- BA34 Fenrir's Forest
update stores set email = 'arlenescateringservices@gmail.com', contact = '0939 979 8930', social_media = 'https://www.facebook.com/arlenescateringservices', logo_url = 'https://graph.facebook.com/arlenescateringservices/picture?type=large' where id = 'store_19_arlene_s_catering';  -- BA35-36 Arlene's Catering
update stores set email = 'hello@heinoahentertainment.com', contact = '0949 706 9877', social_media = 'https://www.facebook.com/heinoahentertainmentandevents', logo_url = 'https://graph.facebook.com/heinoahentertainmentandevents/picture?type=large' where id = 'store_18_heinoah_entertainment';  -- BA37 Heinoah Entertainment
update stores set email = 'jazper.tiongson@gmail.com', contact = '0917 509 0529', social_media = 'https://www.facebook.com/jazpertiongson', logo_url = 'https://graph.facebook.com/jazpertiongson/picture?type=large' where id = 'store_17_jazper_tiongson';  -- BA38 Jazper Tiongson
update stores set email = 'planchesomme@gmail.com, claireperfectcellar@gmail.com', contact = '0917 631 1246', social_media = 'https://www.facebook.com/PlanchenaultSommelier', logo_url = 'https://graph.facebook.com/PlanchenaultSommelier/picture?type=large' where id = 'store_16_perfect_cellar';  -- BA39 Perfect Cellar
update stores set email = 'ledesma.rj@gmail.com', contact = '0917 160 5628', social_media = 'https://www.facebook.com/rjledesma', logo_url = 'https://graph.facebook.com/rjledesma/picture?type=large' where id = 'store_27_rj_ledesma';  -- BA4 RJ Ledesma
update stores set email = 'arstephgananieda1621152827@gmail.com', contact = '0960 441 9968', social_media = 'https://www.facebook.com/SABHairAndMakeUpArtistry', logo_url = 'https://graph.facebook.com/SABHairAndMakeUpArtistry/picture?type=large' where id = 'store_15_sab_hmua';  -- BA40 SAB HMUA
update stores set email = 'craftsmans.sheep@gmail.com', contact = '0954 275 3849', social_media = 'https://www.facebook.com/CraftsmansSheep', logo_url = 'https://graph.facebook.com/CraftsmansSheep/picture?type=large' where id = 'store_28_craftman_s_sheep';  -- BA5 Craftman's Sheep
update stores set email = 'nopeysman@gmail.com', contact = '0975 036 0403', social_media = 'https://www.facebook.com/lovehuesph', logo_url = 'https://graph.facebook.com/lovehuesph/picture?type=large' where id = 'store_ba06_love_hues';  -- BA6 Love Hues
update stores set email = 'ellendrilon@gmail.com', contact = '0927 635 0291', social_media = 'https://www.facebook.com/drilonellen', logo_url = 'https://graph.facebook.com/drilonellen/picture?type=large' where id = 'store_30_ellen_drilon_make_up_group';  -- BA7 Ellen Drilon Make Up Group
update stores set email = 'bloominpinkflowerbar@gmail.com', contact = '0917 540 8575', social_media = 'https://www.facebook.com/BloominPinkFlowerBar', logo_url = 'https://graph.facebook.com/BloominPinkFlowerBar/picture?type=large' where id = 'store_37_bloom_in_pink';  -- BA8 Bloom in Pink
update stores set email = 'abcdtotefulcreations@gmail.com', contact = '0917 186 0168', social_media = 'https://www.facebook.com/profile.php?id=61574399322635', logo_url = 'https://graph.facebook.com/61574399322635/picture?type=large' where id = 'store_45_abcd_toteful_creations';  -- BA9 ABCD Toteful Creations
update stores set email = 'kris.trinidad@mcatering.ph', contact = '0917 872 1079, 0999 187 6296', social_media = 'https://www.facebook.com/mcateringandfinefoods', logo_url = 'https://graph.facebook.com/mcateringandfinefoods/picture?type=large' where id = 'store_01_mcatering';  -- H1-01 Mcatering
update stores set email = '88powerhouse.events@gmail.com', contact = '0917 179 1055, 0938 516 7490', social_media = 'https://www.facebook.com/88powerhouse', logo_url = 'https://graph.facebook.com/88powerhouse/picture?type=large' where id = 'store_02_88_powerhouse_event_mgt_inc';  -- H1-02 88 Powerhouse Event Mgt. Inc.
update stores set email = 't.rexplosive@gmail.com', contact = '0965 941 4715', social_media = 'https://www.facebook.com/adamazing1075', logo_url = 'https://graph.facebook.com/adamazing1075/picture?type=large' where id = 'store_07_dj_adam_wish_107_5';  -- H1-07 DJ Adam WISH 107.5
update stores set email = 'holensph@gmail.com', contact = '0947 801 6860', social_media = 'https://www.facebook.com/holensph', logo_url = 'https://graph.facebook.com/holensph/picture?type=large' where id = 'store_08_crimson_ensemble';  -- H1-08 Crimson Ensemble
update stores set email = 'michiko.riman@gmail.com', contact = '0933 865 4087', social_media = 'https://www.facebook.com/RIMANExclusive', logo_url = 'https://graph.facebook.com/RIMANExclusive/picture?type=large' where id = 'store_13_riman';  -- H1-13 Riman
update stores set email = 'jprosario21499@gmail.com', contact = '0917 149 2149', social_media = 'https://www.facebook.com/profile.php?id=61578596213317', logo_url = 'https://graph.facebook.com/61578596213317/picture?type=large' where id = 'store_34_jp_rosario';  -- H1-34 JP Rosario
update stores set email = 'waw.ofc@gmail.com', contact = '0917 850 1026', social_media = 'https://www.facebook.com/weddingsatwork/', logo_url = 'https://graph.facebook.com/weddingsatwork/picture?type=large' where id = 'store_48_weddings_at_work_w_w';  -- H1-48 Weddings at Work W@W
update stores set email = 'kramzymaranan@gmail.com', contact = '0906 594 0034' where id = 'store_50_mb_visuals';  -- H1-50 MB Visuals
update stores set email = 'hostjaymee@gmail.com', contact = '0954 294 5908', social_media = 'https://www.facebook.com/profile.php?id=61587494203344', logo_url = 'https://graph.facebook.com/61587494203344/picture?type=large' where id = 'store_51_jaymee_antonio';  -- H1-51 Jaymee Antonio
