-- Add 13 new suppliers from SUPPLIERS INFORMATION-2.xlsx
-- (Hall 1 / Birch booths, 88 Powerhouse sub-brands, Peridot sub-brands,
--  Tiger Shoes BA29, and flyering / sponsor partners F2-F5).
-- Logos use the graph.facebook.com/{page}/picture endpoint where a FB
-- page was available; others fall back to a generated DiceBear shape.

insert into stores (id, event_id, name, category, description, logo_url, booth_number, qr_token, passcode, email, contact, social_media) values
  ('store_88ph_flower_delivery', 'evt_fiad_dec25', '88phflowerdelivery', 'Florist & Event Stylist', 'Fresh floral arrangements and bouquets for weddings and events, delivered.', 'https://graph.facebook.com/61577588428247/picture?type=large', 'BI2-A', 'store-qr-88ph-flower-delivery', 'CAWCJC', '88powerhouse.events@gmail.com', '0917 179 1055, 0938 516 7490', 'https://www.facebook.com/profile.php?id=61577588428247'),
  ('store_belle_fete_shoes', 'evt_fiad_dec25', 'Belle Fěte Custom Shoes', 'Couturier & Designer Items', 'Custom-made designer shoes for brides and the entourage.', 'https://graph.facebook.com/61584532000615/picture?type=large', 'BI2-B', 'store-qr-belle-fete-shoes', 'SSRR9G', '88powerhouse.events@gmail.com', '0995 388 4418, 0910 018 3855', 'https://www.facebook.com/profile.php?id=61584532000615'),
  ('store_print8_invitations', 'evt_fiad_dec25', 'Print 8 Invitations', 'Traditional Invitations', 'Traditional printed wedding invitations and stationery.', 'https://api.dicebear.com/7.x/shapes/svg?seed=Print%208%20Invitations', 'BI2-C', 'store-qr-print8-invitations', 'FT5RZN', '88powerhouse.events@gmail.com', '0926 731 8633, 0915 862 9089', null),
  ('store_harmonic_vibes', 'evt_fiad_dec25', 'Harmonic Vibes', 'Musicians - Strings', 'Live string musicians for ceremonies and receptions.', 'https://api.dicebear.com/7.x/shapes/svg?seed=Harmonic%20Vibes', 'BI5', 'store-qr-harmonic-vibes', 'AJ7246', 'villamarinjohnclem@gmail.com', '0938 164 9865', 'https://www.facebook.com/share/1csmPmmeSv/'),
  ('store_peridot_photoman', 'evt_fiad_dec25', 'Peridot Studios', 'Souvenir - Photo Man & Mirror Selfie', 'On-site Photo Man and mirror selfie souvenir booths.', 'https://graph.facebook.com/photomanbyperidotstudios/picture?type=large', 'BI3', 'store-qr-peridot-photoman', 'ZJ6HHH', 'theperidotstudios@gmail.com', '0947 998 1978', 'https://facebook.com/photomanbyperidotstudios'),
  ('store_peridot_video_guestbook', 'evt_fiad_dec25', 'Peridot Video Guestbook', 'Souvenir - Video & Audio Guestbook', 'Video and audio guestbook keepsakes for your celebration.', 'https://graph.facebook.com/videoguestbookbyperidotstudios/picture?type=large', 'BI3-B', 'store-qr-peridot-video-guestbook', 'BPPGPS', 'theperidotstudios@gmail.com', '0947 998 1978', 'https://facebook.com/videoguestbookbyperidotstudios'),
  ('store_rds_lights_sounds', 'evt_fiad_dec25', 'RDS Lights & Sounds Rental', 'Lights & Sounds', 'Lights and sounds equipment rental for events.', 'https://graph.facebook.com/rdslightsandsounds/picture?type=large', 'BI4', 'store-qr-rds-lights-sounds', 'P4VPXX', 'arjiel1994@icloud.com', '0915 364 3326', 'https://www.facebook.com/rdslightsandsounds'),
  ('store_tiger_shoes', 'evt_fiad_dec25', 'Tiger Shoes', 'Designer Shoes', 'Designer footwear for weddings and special occasions.', 'https://api.dicebear.com/7.x/shapes/svg?seed=Tiger%20Shoes', 'BA29', 'store-qr-tiger-shoes', 'NP2ZS9', 'jade_metro1982@yahoo.com.ph', '0908 820 1982', null),
  ('store_88ph_multimedia', 'evt_fiad_dec25', '88 Powerhouse Multimedia', 'Photo & Video', 'Photo, video, livestream, and content creation services.', 'https://graph.facebook.com/61589206746814/picture?type=large', 'BA21B', 'store-qr-88ph-multimedia', 'HHQNXM', '88powerhouse.events@gmail.com', '0917 179 1055, 0917 871 0619', 'https://www.facebook.com/profile.php?id=61589206746814'),
  ('store_prulife_uk', 'evt_fiad_dec25', 'Pru Life UK', 'Insurance', 'Life insurance and financial protection plans.', 'https://api.dicebear.com/7.x/shapes/svg?seed=Pru%20Life%20UK', 'F2', 'store-qr-prulife-uk', '2NFCXW', 'plukruby.bologa@gmail.com', '0917 351 5377', null),
  ('store_soins_wellness', 'evt_fiad_dec25', 'Soins Mobile Wellness', 'Mobile Wellness', 'Home-service nails and massage salon for pre-event pampering.', 'https://api.dicebear.com/7.x/shapes/svg?seed=Soins%20Mobile%20Wellness', 'F3', 'store-qr-soins-wellness', 'VA9UTB', 'partnerships@soinswellness.com', '0961 920 8618', null),
  ('store_metrobank_cards', 'evt_fiad_dec25', 'Metrobank Credit Cards', 'Sponsor - Credit Cards', 'Credit card applications and exclusive cardholder offers.', 'https://api.dicebear.com/7.x/shapes/svg?seed=Metrobank%20Credit%20Cards', 'F4', 'store-qr-metrobank-cards', '2FJR6W', null, '0999 888 5902', null),
  ('store_realty_partner', 'evt_fiad_dec25', 'Real Estate', 'Sponsor - Real Estate', 'Property and real estate investment opportunities.', 'https://api.dicebear.com/7.x/shapes/svg?seed=Real%20Estate', 'F5', 'store-qr-realty-partner', '57ZCWY', null, '0936 951 4936', null)
on conflict (id) do nothing;
