-- Season 2 hourly raffle prize timetable (from the client's schedule doc).
--
-- Only the grand prize and part of Brittany's timetable had been entered:
-- Brittany had 16 of 24 slots and Mella had 1 of 20, so the public schedule
-- page showed Mella as a single card. Backfills the 27 missing rows with the
-- published names, hours, dates and sponsor links.
--
-- Times are stored UTC; the venues run on PH time (UTC+8), so 11am local is
-- 03:00Z. Brittany runs Sep 18-19, Mella Sep 19-20.
--
-- Four rows use a placeholder image because no artwork exists for them yet
-- (Make Up by Jane Martinez x2, the pre-nup photoshoot, Romierre lockets) —
-- upload real photos via Admin -> Raffle Prizes -> Edit.
--
-- Idempotent: re-running changes nothing.

insert into prizes (id, event_id, name, description, image_url, quantity, sponsored_by_store_id, scheduled_at, is_grand, pool_event_ids) values
  ('prize_s2_b1_13', 'evt_fiad_s2_brittany', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-18 05:00:00+00', false, array['evt_fiad_s2_brittany']),
  ('prize_s2_b1_15', 'evt_fiad_s2_brittany', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-18 07:00:00+00', false, array['evt_fiad_s2_brittany']),
  ('prize_s2_b1_19', 'evt_fiad_s2_brittany', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-18 11:00:00+00', false, array['evt_fiad_s2_brittany']),
  ('prize_s2_b1_21', 'evt_fiad_s2_brittany', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-18 13:00:00+00', false, array['evt_fiad_s2_brittany']),
  ('prize_s2_b2_13', 'evt_fiad_s2_brittany', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-19 05:00:00+00', false, array['evt_fiad_s2_brittany']),
  ('prize_s2_b2_15', 'evt_fiad_s2_brittany', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-19 07:00:00+00', false, array['evt_fiad_s2_brittany']),
  ('prize_s2_b2_19', 'evt_fiad_s2_brittany', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-19 11:00:00+00', false, array['evt_fiad_s2_brittany']),
  ('prize_s2_b2_21', 'evt_fiad_s2_brittany', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-19 13:00:00+00', false, array['evt_fiad_s2_brittany']),
  ('prize_s2_m1_11', 'evt_fiad_s2_mella', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-19 03:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m1_13', 'evt_fiad_s2_mella', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-19 05:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m1_15', 'evt_fiad_s2_mella', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-19 07:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m1_17', 'evt_fiad_s2_mella', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-19 09:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m1_19', 'evt_fiad_s2_mella', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-19 11:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m1_12', 'evt_fiad_s2_mella', 'Bridal Booklet', 'Bridal booklet from 88 Powerhouse Event Mgt. Inc.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_uwjjgqsizlel.png', 1, 'store_5gim5rl6bc', '2026-09-19 04:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m1_14', 'evt_fiad_s2_mella', 'Gift Certificate - Make Up', 'Make-up gift certificate from Make Up by Jane Martinez.', 'https://picsum.photos/seed/makeup-jane/400/400', 1, 'store_m6ddwjw8dz', '2026-09-19 06:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m2_11', 'evt_fiad_s2_mella', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-20 03:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m2_13', 'evt_fiad_s2_mella', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-20 05:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m2_15', 'evt_fiad_s2_mella', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-20 07:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m2_17', 'evt_fiad_s2_mella', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-20 09:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m2_19', 'evt_fiad_s2_mella', 'Relationship Planner', 'Exclusive relationship planner from Invitations by Ten.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_e6gqpxa9xinq.jpg', 1, 'store_ijec0vmom4', '2026-09-20 11:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m2_12', 'evt_fiad_s2_mella', 'Bridal Booklet', 'Bridal booklet from 88 Powerhouse Event Mgt. Inc.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_uwjjgqsizlel.png', 1, 'store_5gim5rl6bc', '2026-09-20 04:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m2_14', 'evt_fiad_s2_mella', 'Gift Certificate - Make Up', 'Make-up gift certificate from Make Up by Jane Martinez.', 'https://picsum.photos/seed/makeup-jane/400/400', 1, 'store_m6ddwjw8dz', '2026-09-20 06:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m1_16', 'evt_fiad_s2_mella', 'Free Package Upgrade', 'Free package upgrade from 88phflowerdelivery.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_o3u2df2xg87k.png', 1, 'store_vtmq0utl8q', '2026-09-19 08:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m1_18', 'evt_fiad_s2_mella', 'Free Pre-Nup Studio Photoshoot', 'One free pre-nup studio photoshoot from 88 Powerhouse Multimedia.', 'https://picsum.photos/seed/prenup-photoshoot/400/400', 1, 'store_b8mygjvs2l', '2026-09-19 10:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m1_20', 'evt_fiad_s2_mella', 'Free Photo Session', 'One free photo session from Halcyon Studios.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_ilnc33csrqxp.jpg', 1, 'store_l4jbjjk2gs6n', '2026-09-19 12:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m2_16', 'evt_fiad_s2_mella', 'Customed Bridal Shoes', 'Custom bridal shoes from Belle fete.', 'https://cjhnsyldnzdedgianzsj.supabase.co/storage/v1/object/public/supplier-docs/prize-images/prize_tm43a1ftdvmb.png', 1, 'store_qkv4lhh2aj5u', '2026-09-20 08:00:00+00', false, array['evt_fiad_s2_mella']),
  ('prize_s2_m2_18', 'evt_fiad_s2_mella', 'Lockets and Chains', 'Lockets and chains from Romierre Jewelry.', 'https://picsum.photos/seed/romierre-lockets/400/400', 1, 'store_uvxdfatbeajg', '2026-09-20 10:00:00+00', false, array['evt_fiad_s2_mella'])
on conflict (id) do nothing;

-- 27 rows
